FPS = 60
DELTA_TIME = 1.0 / FPS

CURRENT_VER = "v0.9"

SCREEN_WIDTH = 850
SCREEN_HEIGHT = 478
SCREEN_CENTER = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

LERP_POW = 3 # When lerping figure change transitions the lerp will be powered to this number
TRANSITIONS_SPEED = 0.01
OBSTACLE_SPEED_MULTIPLIER = 1
JUICE_ZOOM = 1.075
JUICE_CENTER_MULTIPLIER = 5

CENTER_POLYGON_RADIUS = 30

# Menu settings
MENU_HEXAGON_RADIUS = 100
